### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by rudy88mph** [tkorlando/parkway#1]
- [x] add vacancies table and form
- [x] Search Engine: search by keywords
- [x] Filter: filter by square footage
